name: Test Build API Project

env:
  API_FOLDER: LilyCmsApi
  
on:
  push:
    branches: [ main ]
    paths:
      - ${{env.API_FOLDER}}/**
  pull_request:
    branches: [ main ]
    paths:
      - ${{env.API_FOLDER}}/**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build ${{env.API_FOLDER}}/LilyCmsApi.sln
