name: Build and Deploy API Project

env:
  BuildConfiguration: Release
  NetCoreVersion: 5.0.x
  ApiFolderPath: LilyCmsApi
  AzureWebAppPackagePath: published-api
  AzureWebAppName: lily-cms-api

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
    paths:
    - LilyCmsApi/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ApiFolderPath }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NetCoreVersion }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BuildConfiguration }}

      - name: Publish
        run: dotnet publish --no-build --configuration ${{ env.BuildConfiguration }} --output ${{ env.AzureWebAppPackagePath }}

      - name: Deploy Api to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AzureWebAppName }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ${{ env.ApiFolderPath }}/${{ env.AzureWebAppPackagePath }}

